version: '3'
services:
    lodex-workers-pytorch:
        container_name: lodex-workers-pytorch
        build:
            context: .
            args:
                - http_proxy
                - https_proxy
        image: inistcnrs/lodex-workers-pytorch:1.0.1
        environment:
            - http_proxy
            - https_proxy
        ports:
            - "31976:31976"
