net:
  port: 27017
  bindIpAll: true

replication:
  replSetName: "rs0"

setParameter:
  mongotHost: localhost:27028
  searchIndexManagementHostAndPort: localhost:27028
  skipAuthenticationToSearchIndexManagementServer: true
  useGrpcForSearch: true

storage:
  dbPath: /data/db
