net:
  port: 27017
  bindIpAll: true

replication:
  replSetName: "rs0"

setParameter:
  mongotHost: 0.0.0.0:27028
  searchIndexManagementHostAndPort: 0.0.0.0:27028
  skipAuthenticationToSearchIndexManagementServer: true
  useGrpcForSearch: true

storage:
  dbPath: /data/db
