version: '3'
services:
    lodex-workers-monitoring:
        container_name: lodex-workers-monitoring
        build:
            context: .
            args:
                - http_proxy
                - https_proxy
        image: inistcnrs/lodex-workers-monitoring:4.0.0
        environment:
            - http_proxy
            - https_proxy
        ports:
            - "31976:31976"
