global:
    scrape_interval: 15s
    evaluation_interval: 15s
    external_labels:
        monitor: 'docker-host-alpha'
        ezmaster_retention_time: "90d"

rule_files:
    - "targets.rules"
    - "host.rules"
    - "containers.rules"

scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 10s
      static_configs:
          - targets: ['localhost:9090']
