FROM golang:1.16.14

ENV NODE_VERSION 16.14.0
ENV ARCH x64
RUN curl http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.3-2_amd64.deb --output libseccomp2_2.5.3-2_amd64.deb && \
	dpkg -i libseccomp2_2.5.3-2_amd64.deb && \
	apt-get clean && \
	apt-get update && \
	apt upgrade -y && \
	apt-get install xz-utils sudo tini build-essential git musl-dev -y && \
	curl -fsSLO --compressed "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-$ARCH.tar.xz" && \
	curl -fsSLO --compressed "https://nodejs.org/dist/v$NODE_VERSION/SHASUMS256.txt" && \
	grep " node-v$NODE_VERSION-linux-$ARCH.tar.xz\$" SHASUMS256.txt | sha256sum -c - && \
	tar -xJf "node-v$NODE_VERSION-linux-$ARCH.tar.xz" -C /usr/local --strip-components=1 --no-same-owner && \
	rm "node-v$NODE_VERSION-linux-$ARCH.tar.xz" SHASUMS256.txt && \
	ln -s /usr/local/bin/node /usr/local/bin/nodejs && \
	node --version && \
	npm --version

RUN wget https://github.com/prometheus/prometheus/archive/refs/tags/v2.33.4.tar.gz
RUN mkdir /src && tar -xf "v2.33.4.tar.gz" -C /src --strip-components=1 --no-same-owner
RUN cd  /src && make build

ADD prometheus.yml /etc/prometheus/

RUN echo '{ \
  "httpPort": 3000, \
  "configPath": "/etc/prometheus/prometheus.yml", \
  "configType": "txt", \
  "dataPath": "/ezdata", \
  "technicalApplication": true \
}' > /etc/ezmaster.json


