# Ces exemples peuvent être exécutés directement dans VSCode, en utilisant l'extension REST Client (humao.rest-client)
# Décommenter/commenter les lignes voulues pour tester localement
# @baseUrl=http://localhost:31976
@baseUrl=http://affiliation-rnsr.tdmservices.intra.inist.fr/

## WS Affiliation - RNSR
POST {{baseUrl}}/v2/affiliation/rnsr?indent=true HTTP/1.1
Content-Type: application/json

[
  {
    "id": 1,
    "value": "UAR 76, Inist-CNRS, 2 rue Jean Zay 54500 Vandoeuvre-lès-Nancy"
  },
  {
    "id": 2,
    "value": "Institut Charles Gerhardt, Université de Montpellier ; UMR 7272 - CNRS, 06100 Nice"
  }
]

###
